In [99]:
import pandas as pd

In [100]:
df = pd.read_csv("../data/tested.csv")

In [101]:
df.head(n = int(input()))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [102]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [103]:
df.shape

(418, 12)

In [104]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

PassengerId - index, числовой признак (уникальный ID)

Survived - категориальный бинарный признак

Pclass - ординальный категориальный признак (класс пассажира), классы (1,2,3) закодированы соотв. цифрами и имеют строгий порядок.

Name - не числовой и не категориальный (текстовый)

Sex - категориальный бинарный признак

Age - числовой (возраст)

SibSp - числовой (кол-во детей)

Parch - числовой (кол-во родителей или детей на корабле)

Ticket - текстовый (код билета)

Fare - числовой (цена плавания)

Cabin - текстовый (код каюты)

Embarked - текстовый (место посадки), но ввиду всего трёх вариаций можно считать категориальным.

In [105]:
NUMERIC_COLS = ["PassengerId", "Age", "SibSp", "Parch", "Fare"]
DESCR_CHARS = ['mean', 'std', '50%', 'min', 'max']

descr = df[NUMERIC_COLS].describe()
descr.loc[DESCR_CHARS]

      PassengerId        Age     SibSp     Parch        Fare
mean  1100.500000  30.272590  0.447368  0.392344   35.627188
std    120.810458  14.181209  0.896760  0.981429   55.907576
50%   1100.500000  27.000000  0.000000  0.000000   14.454200
min    892.000000   0.170000  0.000000  0.000000    0.000000
max   1309.000000  76.000000  8.000000  9.000000  512.329200

In [106]:
df['Pclass'].value_counts()

Pclass
3    218
1    107
2     93
Name: count, dtype: int64

In [107]:
print("Уникальных значений: ", df['Embarked'].nunique())
print("Уникальные значения: ", list(df['Embarked'].unique()))
df['Embarked'].value_counts()

Уникальных значений:  3
Уникальные значения:  ['Q', 'S', 'C']

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

# Контрольный вопрос. Почему Pclass, содержащий целые числа, следует рассматривать как категориальный признак?

Потому что это три класса: 1, 2, 3 - это не числовые значения, а категории качества обслуживания пассажиров закодированные цифрами.

In [108]:
na_cnts = df.isna().sum()
na_perc = ((na_cnts/len(df))*100).round(2)

pd.DataFrame(data = {"cnts": na_cnts, "perc": na_perc}, index=na_perc.index)

             cnts   perc
PassengerId     0   0.00
Survived        0   0.00
Pclass          0   0.00
Name            0   0.00
Sex             0   0.00
Age            86  20.57
SibSp           0   0.00
Parch           0   0.00
Ticket          0   0.00
Fare            1   0.24
Cabin         327  78.23
Embarked        0   0.00

Больше всего пропусков - в столбце Cabin.

В столбце Age - 86 пропусков.

In [109]:
descr_before = df['Age'].describe().loc[DESCR_CHARS]
descr_before['nan_cnt'] = na_cnts['Age']

df['Age'] = df['Age'].fillna(value = df['Age'].median())

descr_after = df['Age'].describe().loc[DESCR_CHARS]
descr_after['nan_cnt'] = df['Age'].isna().sum()

pd.DataFrame(data = {"BEFORE: ": descr_before, "AFTER: ": descr_after}, index=descr_before.index)

          BEFORE:     AFTER:
mean     30.272590  29.599282
std      14.181209  12.703770
50%      27.000000  27.000000
min       0.170000   0.170000
max      76.000000  76.000000
nan_cnt  86.000000   0.000000

In [110]:
print("Строк и столбцов до дропа: ", df.shape)

df = df.dropna(subset=['Embarked'])
if na_perc['Cabin'] > 50:
    df = df.drop(labels = "Cabin", axis=1)

print("Строк и столбцов после дропа: ", df.shape)

Строк и столбцов до дропа:  (418, 12)
Строк и столбцов после дропа:  (418, 11)

Ответы на вопросы по данным:

- Медиана может быть предпочтительнее среднего при заполонении пропусков потому, что устойчива к выбросам. В больнице средняя температура может быть 36.6, но кто-то лежит в морозильнике морга, а кто-то в палате интенсивной терапии с температурой 40+. Медиана же даёт число посередине списка, тем самым создавая "типичные" значения, не отклоняющиеся в сторону выбросов.

- При заполнении медианой медиана (50% перцентиль) не изменилась, также как и минимум и максимум, остальные изменились.

- Стандартное отклонение изменилось вследствии изменения среднего значения по столбцу в целом, вызванного заменой NaN на медиану.

- Нет, исходное распределение возрастов при заполнении медианой не сохранится. Из-за такого заполнения вероятность получить человека с медианным возрастом увеличится.

In [115]:
print("Процент выживших: ", round((df['Survived'].sum() / len(df)) * 100, 2))

Процент выживших:  36.36

In [131]:
df.groupby(['Survived', 'Sex']).size()

Survived  Sex
0         male      266
1         female    152
dtype: int64

In [136]:
df.groupby(['Sex'])['Age'].mean()

Sex
female    29.734145
male      29.522218
Name: Age, dtype: float64

In [139]:
df.groupby(['Survived', 'Sex'])['Age'].mean()

Survived  Sex
0         male      29.522218
1         female    29.734145
Name: Age, dtype: float64

In [140]:
print(" Стоимость билета min/max/mean:  ", df['Fare'].min(), df['Fare'].max(), df['Fare'].mean())

 Стоимость билета min/max/mean:   0.0 512.3292 35.627188489208635

In [141]:
print("Стандартное отклонение возраста: ", df['Age'].std())

Стандартное отклонение возраста:  12.70376984633328

Контрольный вопрос. 

Главная разница мужчин и женщин (в рамках этого набора данных) заключается в том, что погибли все мужчины, а все женщины выжили.

In [147]:
df_sel = df[((df['Age'] > 30) & (df['Pclass'] == 1))]
print("Всего: ", len(df_sel))
df_sel.head(10)

Всего:  70

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,S
20,912,0,1,"Rothschild, Mr. Martin",male,55.0,1,0,PC 17603,59.4000,C
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,S
44,936,1,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.0,1,0,11753,52.5542,S
46,938,0,1,"Chevre, Mr. Paul Romaine",male,45.0,0,0,PC 17594,29.7000,C
48,940,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,C
59,951,1,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,C
67,959,0,1,"Moore, Mr. Clarence Bloomfield",male,47.0,0,0,113796,42.4000,S

In [152]:
df_sel = df[((df['Age'] < 18) | (df['Sex'] == "female")) & (df['Survived'] == 1)]
print("Всего: ", len(df_sel))
df_sel.head(10)

Всего:  152

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,Q
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,C
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,S
15,907,1,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1,0,SC/PARIS 2167,27.7208,C
18,910,1,3,"Ilmakangas, Miss. Ida Livija",female,27.0,1,0,STON/O2. 3101270,7.9250,S
19,911,1,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.0,0,0,2696,7.2250,C
22,914,1,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,27.0,0,0,PC 17598,31.6833,S

In [154]:
cl3_mean = df.groupby("Pclass")['Fare'].mean()[3]
df_sel = df[(df['Pclass'] == 3) & ((df['Fare']) > cl3_mean)]
print("Всего: ", len(df_sel), " Средняя цена за третий класс: ", cl3_mean)
df_sel.head(10)

Всего:  62  Средняя цена за третий класс:  12.45967788018433

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,S
25,917,0,3,"Robins, Mr. Alexander A",male,50.0,1,0,A/5. 3337,14.5000,S
29,921,0,3,"Samaan, Mr. Elias",male,27.0,2,0,2662,21.6792,C
32,924,1,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.0,1,2,C.A. 2315,20.5750,S
33,925,1,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,27.0,1,2,W./C. 6607,23.4500,S
39,931,0,3,"Hee, Mr. Ling",male,27.0,0,0,1601,56.4958,S
40,932,0,3,"Karun, Mr. Franz",male,39.0,0,1,349256,13.4167,C
49,941,1,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36.0,0,2,C.A. 37671,15.9000,S
55,947,0,3,"Rice, Master. Albert",male,10.0,4,1,382652,29.1250,Q
58,950,0,3,"Davison, Mr. Thomas Henry",male,27.0,1,0,386525,16.1000,S

In [155]:
df_sel = df[(20 <= df['Age']) & (df['Age'] <= 40) & ((df['Embarked']) == "S")]
print("Всего: ", len(df_sel), " Средняя цена за третий класс: ", cl3_mean)
df_sel.head(10)

Всего:  179  Средняя цена за третий класс:  12.45967788018433

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,S
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,S
10,902,0,3,"Ilieff, Mr. Ylio",male,27.0,0,0,349220,7.8958,S
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,S
18,910,1,3,"Ilmakangas, Miss. Ida Livija",female,27.0,1,0,STON/O2. 3101270,7.9250,S
22,914,1,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,27.0,0,0,PC 17598,31.6833,S
31,923,0,2,"Jefferys, Mr. Clifford Thomas",male,24.0,2,0,C.A. 31029,31.5000,S
32,924,1,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.0,1,2,C.A. 2315,20.5750,S

Контрольный вопрос.

И (&) требует соблюдения ВСЕХ перечисленных условий для данной строки, чтобы она была включена в результируюший индекс, а ИЛИ (|) хотя-бы одного.

In [180]:
group_1 = df.groupby(by=["Pclass", "Sex"])[["PassengerId", "Age", "Fare", "Survived"]]
group_1_agg_res = group_1.aggregate(func={"PassengerId": 'count', "Age": 'mean', "Fare": 'mean', "Survived": 'mean'}) 
group_1_agg_res['Survived'] = round(group_1_agg_res['Survived']*100, 2)
group_1_agg_res.to_csv("../res/titanic_statistics.csv")
group_1_agg_res

               PassengerId        Age        Fare  Survived
Pclass Sex
1      female           50  40.760000  115.591168     100.0
       male             57  38.859649   75.586551       0.0
2      female           30  24.464000   26.438750     100.0
       male             63  30.690476   20.184654       0.0
3      female           72  24.273194   13.735129     100.0
       male            146  25.372671   11.826350       0.0

In [181]:
group_2 = df.groupby(by=["Embarked"])[["PassengerId","Survived"]]
group_2_agg_res = group_2.aggregate(func={"PassengerId": 'count', "Survived": 'mean'}) 
group_2_agg_res['Survived'] = round(group_2_agg_res['Survived']*100, 2)
group_2_agg_res

          PassengerId  Survived
Embarked
C                 102     39.22
Q                  46     52.17
S                 270     32.59

In [182]:
group_1 = df.groupby(by=["Pclass"])[["Survived"]]
round(group_1.mean()*100, 2)

        Survived
Pclass
1          46.73
2          32.26
3          33.03

В 1 классе людей выжило больше всего (в % соотношении)

Контрольный вопрос.

Группировка просто раскладывает данные по требуемым категориям, тогда как фильтрация выбирает только те, что подходят по фильтру.

In [183]:
df.to_csv("../res/titanic_processed.csv")

# Выводы

1) Больше всего пропусков - Cabin, Age, Fare (соотв. в порядке убывания)
2) Данных стало меньше так как часть столбцов и строк были удалены. После заполнения пропусков возраста медианой уменьшилось стандарнтное отклонение и среднее значение.
3) Все женщины выжили, все мужчины погибли.
4) В 1 классе наибольшая доля выживших.
5) Возможность того, что это не Excel. А также группировка, фильтрация, аггрегация, векторизованные функции.